server:
  port: 8089
spring:
  redis:
    host: 47.93.21.164
    port: 6379
    password: 123456
    timeout: 5000
  datasource:
    password: test_ecs
    username: test_ecs
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.21.164:3306/test_ecs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull




